-- RenameEnumValue
ALTER TYPE "OrderStatus" RENAME VALUE 'PROCESSING' TO 'CONFIRMED';
ALTER TYPE "OrderStatus" RENAME VALUE 'COMPLETED' TO 'DELIVERED';

-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE 'SHIPPED' AFTER 'CONFIRMED';
